// Generated by gencpp from file magangros/PosisiTurtle.msg
// DO NOT EDIT!


#ifndef MAGANGROS_MESSAGE_POSISITURTLE_H
#define MAGANGROS_MESSAGE_POSISITURTLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace magangros
{
template <class ContainerAllocator>
struct PosisiTurtle_
{
  typedef PosisiTurtle_<ContainerAllocator> Type;

  PosisiTurtle_()
    : x(0.0)
    , y(0.0)  {
    }
  PosisiTurtle_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::magangros::PosisiTurtle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::magangros::PosisiTurtle_<ContainerAllocator> const> ConstPtr;

}; // struct PosisiTurtle_

typedef ::magangros::PosisiTurtle_<std::allocator<void> > PosisiTurtle;

typedef boost::shared_ptr< ::magangros::PosisiTurtle > PosisiTurtlePtr;
typedef boost::shared_ptr< ::magangros::PosisiTurtle const> PosisiTurtleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::magangros::PosisiTurtle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::magangros::PosisiTurtle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::magangros::PosisiTurtle_<ContainerAllocator1> & lhs, const ::magangros::PosisiTurtle_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::magangros::PosisiTurtle_<ContainerAllocator1> & lhs, const ::magangros::PosisiTurtle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace magangros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::magangros::PosisiTurtle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::magangros::PosisiTurtle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magangros::PosisiTurtle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::magangros::PosisiTurtle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magangros::PosisiTurtle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::magangros::PosisiTurtle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::magangros::PosisiTurtle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::magangros::PosisiTurtle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x209f516d3eb691f0ULL;
  static const uint64_t static_value2 = 0x663e25cb750d67c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::magangros::PosisiTurtle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "magangros/PosisiTurtle";
  }

  static const char* value(const ::magangros::PosisiTurtle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::magangros::PosisiTurtle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"\n"
;
  }

  static const char* value(const ::magangros::PosisiTurtle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::magangros::PosisiTurtle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PosisiTurtle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::magangros::PosisiTurtle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::magangros::PosisiTurtle_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAGANGROS_MESSAGE_POSISITURTLE_H
